### ISSUE TITLE
Report median (or distribution) of # of features per subject used in PS building

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortMethod#100]
A reviewer recently requested this statistic, and it seems useful.

**Comment by schuemie** [comment]
The median of the number of non-zero covariates per person, regardless of their coefficients in the propensity model? Or restricting only to those with beta <> 0?

**Comment by msuchard** [comment]
Initial idea was median(non-zero covariates regardless of coefficient) [for some other distributional info]

**Comment by schuemie** [comment]
Hmmm, this code (where `object` is a CohortMethodData object) computes the statistic you want:

```r
medianCovariateValueCount <- object$covariates %>%
    group_by(.data$rowId) %>%
    summarise(count = count()) %>%
    ungroup() %>%
    pull(.data$count) %>%
    median()
```

I thought I'd just add this to the `summary()` method for CohortMethodData, but it takes 30 seconds to run on a medium-sized object, which is too long to wait for `summary()` to respond.

If we create an index on rowId:

```r
DBI::dbExecute(object, "CREATE INDEX idx ON covariates(rowId);")
```

It takes 2 seconds to run, but creating the index takes 40 seconds.

We can certainly compute this statistic when exporting in the [skeleton](https://github.com/OHDSI/SkeletonComparativeEffectStudy), where the wait time wouldn't be a problem. Or we can have FeatureExtraction create the index when pulling the covariate data from the server...
