### ISSUE TITLE
excludeCovariateIds not excluded from propensity score model

### ISSUE THREAD

**Issue by rekkasA** [OHDSI/CohortMethod#101]
I noticed that the covariate IDs that I want to manually exclude from the propensity score are not actually excluded. Could it be that lines 100-103 of PsFunctions.R (master):
```
if (length(excludeCovariateIds) != 0) {
      covariates <- covariates %>%
        filter(!.data$covariateId %in% includeCovariateIds)
    }
```
should be
```
if (length(excludeCovariateIds) != 0) {
      covariates <- covariates %>%
        filter(!.data$covariateId %in% excludeCovariateIds)
    }
```
to actually filter out the desired covariates?

**Comment by schuemie** [comment]
Thanks! Yes, I'll fix that
