### ISSUE TITLE
Improve performance of calculate balance for large cohort

### ISSUE THREAD

**Issue by chandryou** [OHDSI/CohortMethod#109]
When we conduct a very large-scale analysis, eg LEGEND-HTN, I think most of time is consumed at 'computing covariate balance', since we use only sampled population to calculate propensity score but calculate the balance by using whole population in the cohort. Usually, it does not matter, but it becomes problematic when we deal with a cohort with more than a million of subjects. 

Would there be a way to improve the performance of this step, or should we allow to calculate the balance of sampled population?

**Comment by schuemie** [comment]
Yes, I just added sampling before covariate balance computation to the develop branch. Feel free to give it a try.

**Comment by schuemie** [comment]
(I recommend using the default setting of 250,000 subjects per cohort)

**Comment by chandryou** [comment]
This issue was closed by this commit of Dr. Schumie. Thank you. 
https://github.com/OHDSI/CohortMethod/commit/ce465701b8d58f7636b08cc83a45933f7ba82200
