### ISSUE TITLE
"removeDuplicateSubjects": "remove all" results in query hanging on postgres

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortMethod#111]
In trying to run [this study](https://github.com/oxford-pharmacoepi/ROC22_CovVaxComparativeSafety/tree/main/CovVaxComparativeSafety) from @Xintong-Li-ZnCu the analysis was hanging (2+days stuck at 33% of a query) after calling CohortMethod::runCmAnalyses [here](https://github.com/oxford-pharmacoepi/ROC22_CovVaxComparativeSafety/blob/49d30a23af4b69b1a515649d16b51f376d290a46/CovVaxComparativeSafety/R/CohortMethod.R#L34). This was using data from sidiap where we have 2 million people in the target cohort and around 800,000 in the comparator and we are using postgres. 

Looking into it, this only happens when we have "removeDuplicateSubjects": "remove all". When set to "removeDuplicateSubjects": "keep all" this no longer happens. It seems the line of sql that causes the problem for us at sidiap is this one: https://github.com/OHDSI/CohortMethod/blob/79b86e4435f66825cecfc8e518d0d1d034d3d4ef/inst/sql/sql_server/CreateCohorts.sql#L149. Apparently this "COUNT(DISTINCT ..." is [known to be somewhat slow](https://stackoverflow.com/questions/11250253/postgresql-countdistinct-very-slow), although I´m not sure it would be expected to hang as we are experiencing.

**Comment by msuchard** [comment]
@edward-burn  -- thanks for tracking this down!   For @Xintong-Li-ZnCu 's study, we can remove subjects later in the code (on the local machine side) to get past this hiccup.

At'ing @schuemie here so he's aware.

**Comment by msuchard** [comment]
Specifically, you can set `removeDuplicationSubjects = FALSE` under `getDbCohortMethodDataArgs` and then set `removeDuplicateSubjects = "remove all" under the `createStudyPopArgs`.    @Xintong-Li-ZnCu

**Comment by schuemie** [comment]
Yes, I've already observed the Postgres query optimizer to be really dumb. 

Marc's solution is a good one. A nice experiment would be to call `ANALYZE` on the cohort table before running CohortMethod instead to see if that helps. In that case, we may consider obsessive compulsive calling of `ANALYZE` on all tables in Postgres.
