### ISSUE TITLE
`njava.lang.OutOfMemoryError: Java heap space` on large data asset with parallel analysis

### ISSUE THREAD

**Issue by BlingArida** [OHDSI/CohortMethod#113]
Hello developers,

Hope you are doing well.

I am working on one study and the `CohortMethod` is one dependency package for the PLE study.

Since our data asset is extremely huge, it encountered with `njava.lang.OutOfMemoryError: Java heap space`. 

Even though I increased heap size of JVM, it didn't work on paralleled threads - those working threads still with default heap size. So whatever I set in `codeToRun.R`, nothing changed. It occured with `njava.lang.OutOfMemoryError: Java heap space` again and again.

Could you help set up java parameter inside the package? 
Or is there any way could help me to run this study? I thought perhalps set `maxCore<-1` would help..

Appreciate for any ideas!

Best,
Can

**Comment by msuchard** [comment]
@BlingArida -- it should be possible to set the `rJava` environment in each of the task threads using a mechanism similar to that which we use to pass the `Andromeda` temp folder here:

https://github.com/OHDSI/ParallelLogger/blob/c75a81141d1da1c4ff2fc7822c4d10fa7b0951dc/R/Cluster.R#L70

To try this out, I'd suggesting passing whatever `rJava::.jinit()` you'd like about here: 

https://github.com/OHDSI/ParallelLogger/blob/c75a81141d1da1c4ff2fc7822c4d10fa7b0951dc/R/Cluster.R#L20

If this functionality helps, then we can discuss adding such functionality permanently into `ParallelLogger` / `CohortMethod`.
