### ISSUE TITLE
Filtering unbalanced covariates for outcome model?

### ISSUE THREAD

**Issue by ted9219** [OHDSI/CohortMethod#133]
Hi,

When we want to apply the double adjustment for unbalanced covariates in the outcome model, is there any function which filters covariates unbalanced (aSMD > 0.1) only?

I think the unbalanced covariates are different from each T-C-O-analysis setting pair, I couldn't input the covariate_ids for each analysis into the cmAnalysis.json file.

**Comment by schuemie** [comment]
This is currently not supported when using the multi-analysis approach (i.e., when running `runCmAnalyses()`, at least not automatically in one go.

You can definitely do it when calling `fitOutcomeModel()` manually, using the `includeCovariateIds` and setting `useCovariates = TRUE`. 

Or you could run `runCmAnalyses()` without including the covariates, delete the model files (the 'Analysis_x' folders), and specify the covariates when calling `createFitOutcomeModelArgs()`. Then run `runCmAnalyses()` again to refit the models with the covariates.

**Comment by schuemie** [comment]
I'm aware that this is a common thing to do, but of course a major downside is that you have no diagnostics to show that after including the covariates in the outcome model you are now adjusting for them appropriately. So in general I recommend against it.

**Comment by ted9219** [comment]
Thank you for your comment. I agree with your opinion. Yes, we don't have any diagnostics after adjusting covariates in the outcome model. More research methods are needed to adjust for unbalanced covariates after matching or stratification.
