### ISSUE TITLE
Refactor createStudyPopulation

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortMethod#135]
The `createStudyPopulation()` is a bit hard to read. It would probably help if most the functionality was rewritten using dplyr.

**Comment by mvankessel-EMC** [comment]
Hi @schuemie I 'dplyrfied' some of the code in the [is135-createStudyPopulation](https://github.com/OHDSI/CohortMethod/blob/is135-createStudyPopulation/) branch.

**Comment by schuemie** [comment]
Looks good! Did you run the unit tests on this?

Would you mind removing any mention of `dplyr::`? I recently removed those, since we [fully import dplyr](https://github.com/OHDSI/CohortMethod/blob/main/R/CohortMethod.R#L35), and I think the code looks prettier without it.
