### ISSUE TITLE
Unexpected columns are created using matchOnPsAndCovariates - solution removing hardcoded concepts in mergeCovariatesWithPs

### ISSUE THREAD

**Issue by awrosen** [OHDSI/CohortMethod#139]
Dear CohortMethod team,

Thank you for an excellent package.

I've encountered a problem when I've trued using the matchOnPsAndCovariates() function, namely that the covariates I choose is not included in the data frame produced, instead the covariates 2018006 and 8527004 are included.

I've solved the problem locally by modifying the mergeCovariatesWithPs function from PsFunctions.R (https://github.com/OHDSI/CohortMethod/blob/main/R/PsFunctions.R, line 875 - 879), which states:

mergeCovariatesWithPs <- function(data, cohortMethodData, covariateIds) {
  covariateIds <- c(2018006, 8527004)
  covariates <- cohortMethodData$covariates %>%
    filter(.data$covariateId %in% covariateIds) %>%
    collect()

Here I've changed the code specifying the covariatesIds parameter to:

mergeCovariatesWithPs <- function(data, cohortMethodData, covariateIds) {
  covariateIds <- covariateIds
  covariates <- cohortMethodData$covariates %>%
    filter(.data$covariateId %in% covariateIds) %>%
    collect()

Which works for me.

KR

Andreas

**Comment by schuemie** [comment]
Yikes! Obviously that should not be there. Thanks for the fix, it will be included in the next release.
