### ISSUE TITLE
Better implement behavior in fitOutcomeModel() when combining useCovariates with interaction terms

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortMethod#140]
See comment added here: https://github.com/OHDSI/CohortMethod/commit/4954438cc7e0b41c0acca959c3bc66c686c9bd1b

@mvankessel-EMC

**Comment by mvankessel-EMC** [comment]
Thanks I'll have a look.

**Comment by mvankessel-EMC** [comment]
I've attached the issue branch, and made changes.

1. **don't remove main effect is useCovariates = TRUE**
I've wrapped the removal of the covariateIds in a check that checks if `useCovariates` == FALSE [link](https://github.com/OHDSI/CohortMethod/blob/is140-fitOutcomeModel/R/OutcomeModels.R#L291-L296).
2. **check if main effect covariate exists in data**
To be fair I wasn't entirely sure what you meant with this. I checked if the mainEffectTerms exist in the covariateData, re-using logic earlier in the function. If it does not exist, it'll print a message [link](https://github.com/OHDSI/CohortMethod/blob/is140-fitOutcomeModel/R/OutcomeModels.R#L214-L224).

**Comment by schuemie** [comment]
1 looks good. 2 we probably should either throw an error or add the main effects. (Throwing an error is probably good enough)

**Comment by mvankessel-EMC** [comment]
I've replaced the `message` with `stop`. The message itself remains the same. 067e5ddcc040e1b069ef7f8df8b6ab6b8c818513

**Comment by schuemie** [comment]
Thanks. Can you create a PR?
