### ISSUE TITLE
Error unused argument (outcomeIds = outcomeIds)

### ISSUE THREAD

**Issue by skanskan** [OHDSI/CohortMethod#145]
Hello.

I have defined a Population Study comparing two cohorts in Atlas and I have exported it as a package.
I have configured the connection but when I run it I get this error related with CohortMethod:

`execute(connectionDetails, all configuration)`

```
Creating exposure and outcome cohorts
Connecting using SQL Server driver
Creating cohort: ISTIA_Cohort_BMS_Study_Carlos
  |=====================| 100%
Executing SQL took 12.3 secs
Creating cohort: Cohorte_ACS_Julian_BMS
  |======================| 100%
Executing SQL took 52.5 secs
Creating cohort: Fallecidos
  |======================| 100%
Executing SQL took 6.39 secs
Creating negative control outcome cohorts
  |===============| 100%
Executing SQL took 6.75 secs
Counting cohorts
Running CohortMethod analyses
An error report has been created at  ./errorReportR.txt
Error in CohortMethod::createTargetComparatorOutcomes(targetId = targetId, :
unused argument (outcomeIds = outcomeIds)
```

And errorreportR.txt contains this information:

```
Thread: Main
Message:  unused argument (outcomeIds = outcomeIds)
Level:  FATAL
Time:  2023-07-12 12:22:20

Stack trace:
7: h(simpleError(msg, call))
6: CohortMethod.R#160: .handleSimpleError(function (condition) 
{
    if (is(condition, "error")) {
       
5: FUN(X[[i]], ...)
4: CohortMethod.R#167: lapply(1:nrow(tcs), createTco)
3: CohortMethod.R#58: createTcos(outputFolder = outputFolder)
2: Main.R#123: runCohortMethod(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSch
1: execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, cohortDatabaseS

R version:
R version 4.2.3 (2023-03-15 ucrt)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- PruebaAF (0.0.1)
- DatabaseConnector (6.2.3)


```

How can avoid this error?

**Comment by schuemie** [comment]
It seems there is a mismatch between the version of CohortMethod and your study package. Did the study package come with a renv lock file? If so, you would need to run `renv::restore()` to make sure you have the right version of CohortMethod. Right now it seems like you're running an old study package with the latest version of CohortMethod.

**Comment by skanskan** [comment]
OK, I have downgraded CohortMethod and now it doesn't produce the aforementioned error, it creates all csv files properly, though at the end the shiny application doesn't work, I don't know if it's related.
On my work computer renv doesn't work due to lack of admin privileges, then I have to disable it.
