### ISSUE TITLE
CohortMethodData is read from env cache even when the covarieSettings have changed within the same R session

### ISSUE THREAD

**Issue by SulevR** [OHDSI/CohortMethod#157]
`getCohortMethodData()` loads old cohortMethodData even when the `covariateSettings` have changed.

When` getCohortMethodData()` is called (for instance, from `runCmAnalyses()` when running multiple analyses), it first checks whether a `cohortMethodData` object exists in R cache and if so, it does not read it from the zip file. Even when it reads it from zip file, the covariateSettings may have changed and the zip file contents is not correct anymore.

This causes a problem when one runs analyses and then decides to change the covariate settings (for instance, add some concepts to the exclusion list) without restarting R session (clearing the cache). Even when they change the exclusion list (and it seems that the new covariates are fetched from the server), the cohortMethodData file that is actually used, is taken from the cache, which is built by using the previous settings. Therefore, the results do not correspond anymore to the new settings actually executed.

I think the cache file should be removed whenever the covariate settings have changed. Currently, it is very confusing why the exclusion list does not apply. It was time-consuming also to understand that it uses environment cache in addition to zip file (I tried to remove zip file before running the analyses but it did not help).

I did not check but I'm afraid that also the zip file is not updated when `covariataSettings` have changed. And perhaps it affects also other files that are created from the previous cohortMethodData.

I attach the R code I used to replicate this issue by using `Eunomia` dataset.

[Bug_CM_cache2.R.zip](https://github.com/OHDSI/CohortMethod/files/13888447/Bug_CM_cache2.R.zip)

**Comment by schuemie** [comment]
Yes, basically whenever you change the settings you should delete the folder. Are you imagining some automated check that does this for you? This could be very simple (if old settings != new settings delete all), or could become very complicated very quickly

**Comment by SulevR** [comment]
1. Deleting the folder does not help as the object is taken from the environment cache.
2. Yes, I think the package should always remove all files and objects from the cache if covariateSettings have changed.

**Comment by schuemie** [comment]
Ah, yes, if you're not using multi-threading and haven't restarted R, the cache will still be populated. Good catch. I'll put together some code for this. I'll probably make it interactive, and only delete if the user says ok. There are a few use cases where (advanced) users want to keep the files,
