### ISSUE TITLE
launchResultsViewer is not compatible with the latest ShinyAppBuilder

### ISSUE THREAD

**Issue by ggamit** [OHDSI/CohortMethod#169]
In function launchResultsViewer (Viewer.R) there's a call to ShinyAppBuilder::createDefaultCohortMethodConfig()
This function has been removed from ShinyAppBuilder, replaced by CreateDefaultEstimationConfig()
(see https://github.com/OHDSI/ShinyAppBuilder/commit/cfa26a4e284e089181b7c8d0c24cd3dcbe9b0f29)
So the the current code fails to load the shiny viewer, unless ShinyAppBuilder is downgraded.

**Comment by schuemie** [comment]
This was the subject of the latest release (4 days ago), so should be fixed now
