### ISSUE TITLE
Change schema calls to allow different SQL Server schemas inside of database

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#19]
SQL Server has database and schema.  Currently our SQL assumes the schema is 'dbo'.  We can remove this assumption, thereby require SQL Server users to put 'DBName.SchemaName' in the string for the cdmSchema and resultsSchema parameters.  Then, when this code is rendered for SQL Server, it will flexibly work for all database/schema, and when translated to Oracle/Postgres, the schema (if .dbo) could be removed and not included.

Will make this change after we have a stable version working, because it'll change all our current calls to getDBCohortData used in our development.

**Comment by schuemie** [comment]
Fixed in commit 9229200ac5a8782b480c97bffb15aa92ee469e81
