### ISSUE TITLE
Allow covariates to be created for limited subset of CONCEPTs within a table

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#20]
Right now, creating CONDITION covariates creates all available CONDITIONs, but there may be instances where a user wants to only include a small subset of concepts.  An additional parameter would be required to allow this filtering.
 
Same would apply to DRUGs, PROCEDUREs, OBSERVATIONs.

**Comment by schuemie** [comment]
We now have the `includedCovariateConceptIds` that can specify a limited set of concept IDs for which to construct covariates across the domains. I don't think we'll add extra options to specify this per domain. Please reopen if you think this would be useful.
