### ISSUE TITLE
Add era construction function

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortMethod#29]
Often we'd like to define our treatment and comparator cohorts not as a single drug, but a combination (e.g. drug classes comprising multiple drugs). In that case it is important to construct correct eras (periods of non-overlapping continuous use of the drug) for those combinations of exposures. SQL for performing this task is floating around OHDSI, but should ideally be captured in a function. This could live in the CohortMethod package for now, although it is a function that is generic to all methods.

**Comment by yueqinzhao** [comment]
It would be great if this is created as a function that can be used routinely.

**Comment by schuemie** [comment]
Implemented in the develop branch
