### ISSUE TITLE
change SQL in getOutcomes to SELECT INTO instead of INSERT statements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#31]
SELECT INTO or CTAS queries seem more efficient that creating a table and then inserting records into it.  We definitely can do this in getOutcomes, it's a bit less clear how to optimize getCovariates.

**Comment by schuemie** [comment]
Fixed with this commit: #f806c7019fcc607bcb9905ba8c07f780507a18bb
