### ISSUE TITLE
Error on getPsModel

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/CohortMethod#35]
Let me know if I can provide any additional details.

> propensityModel <- getPsModel(results, cohortData)
Error in abs(cfs$coefficient) : 
  non-numeric argument to mathematical function
In addition: Warning message:
In merge.ffdf(ff::as.ffdf(cfs), cohortData$covariateRef, by.x = "id",  :
  No match found, returning NULL as ffdf can not contain 0 rows

> traceback
function (x = NULL, max.lines = getOption("deparse.max.lines")) 
{
    if (is.null(x) && !is.null(x <- get0(".Traceback", envir = baseenv()))) {
    }
    else if (is.numeric(x)) 
        x <- .Internal(traceback(x))
    n <- length(x)
    if (n == 0L) 
        cat(gettext("No traceback available"), "\n")
    else {
        for (i in 1L:n) {
            label <- paste0(n - i + 1L, ": ")
            m <- length(x[[i]])
            if (!is.null(srcref <- attr(x[[i]], "srcref"))) {
                srcfile <- attr(srcref, "srcfile")
                x[[i]][m] <- paste0(x[[i]][m], " at ", basename(srcfile$filename), 
                  "#", srcref[1L])
            }
            if (m > 1) 
                label <- c(label, rep(substr("          ", 1L, 
                  nchar(label, type = "w")), m - 1L))
            if (is.numeric(max.lines) && max.lines > 0L && max.lines < 
                m) {
                cat(paste0(label[1L:max.lines], x[[i]][1L:max.lines]), 
                  sep = "\n")
                cat(label[max.lines + 1L], " ...\n")
            }
            else cat(paste0(label, x[[i]]), sep = "\n")
        }
    }
    invisible(x)
}
<bytecode: 0x000000001505bed0>
<environment: namespace:base>

**Comment by schuemie** [comment]
My first guess is that `results` is not a valid object as generated by `createPs`, suggesting the problem already occurred earlier. Could you try
```r
str(attr(results, "coefficients"))
```
and see if it confirms it is a `Named num`? If not, can you see if `createPs` threw an error?

**Comment by fdefalco** [comment]
> str(attr(results,"coefficients"))
 Named num [1:1547] -1.19 0 0 0 0 ...
 - attr(*, "names")= chr [1:1547] "(Intercept)" "17" "18" "19" ...

It appears to be a Named num, createPs did not throw any errors.

**Comment by schuemie** [comment]
Ah, I'm guessing all coefficients except the intercept are 0. Are you by any chance using a really small example data set?

**Comment by fdefalco** [comment]
Yes, that does appear to be the case when I look at the data coming back from attr(results,"coefficients").  I'm not sure what is considered small, but in this case I have 11k people in my target cohort, 38k in my comparator and 3k in the outcome cohort.  I'll email you the R code so you can check it out first hand.

**Comment by schuemie** [comment]
We figured out that this was caused by not excluding the target and comparator drugs from the covariates. The new version of CohortMethod will mention the need for this more clearly.
