### ISSUE TITLE
plotPS enhancements: adding information about equipoise

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#40]
On the propensity score distribution plot, could we add some statistics like:
- total cohort size in treated/comparator  (perhaps "n=xxx' on the legend)
- % of treated/comparator group in clinical equipoise (e.g. % with 0.4<=PrefScore<=0.6)
- % of treated/comparator group without overlap

**Comment by schuemie** [comment]
Duplicate of https://github.com/OHDSI/CohortMethod/issues/67
