### ISSUE TITLE
CohortMethod plots:  allow users to add titles?

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#41]
I would like to add a title to the various plots, something that allows me to define the name of the treated/comparator group and also, if applicable, details which analysis the graph refers to.  I have achieved this in the past by saving the plot object and then adding ggtitle() before saving it, but this can cause some annoying formatting issues, particularly if the title is long or multi-lined.  would it be possible to have 'title' parameter on our graphs that could format better?

**Comment by schuemie** [comment]
I've added the option to specify names for the treatment and comparator cohorts in all plots. Specifying the overall plot title seems like something for the document in which you embed the plot, so not supporting right now.
