### ISSUE TITLE
Error When Running CM Analysis

### ISSUE THREAD

**Issue by jduke99** [OHDSI/CohortMethod#43]
I received this error when running CM (tough to get after 9.72 hours! :) ):

Error in UseMethod("open") : 
  no applicable method for 'open' applied to an object of class "data.frame"

Here is the full output, and below is my study configuration:

Connecting using Oracle driver

Constructing treatment and comparator cohorts
Executing multiple queries. This could take a while
  |==================================================================================================================================| 100%
Analysis took 0.822 secs
Fetching data from server
Loading took 2.56 secs
Constructing default covariates
  |==================================================================================================================================| 100%
Analysis took 9.72 hours
Done
Fetching data from server
Loading took 4.11 mins
Removing redundant covariates
Normalizing covariates

Constructing outcomes
Executing multiple queries. This could take a while
  |==================================================================================================================================| 100%
Analysis took 6.27 secs
Done
Fetching data from server
Loading took 0.306 secs
Error in UseMethod("open") : 
  no applicable method for 'open' applied to an object of class "data.frame"
In addition: Warning message:
In lowLevelQuerySql.ffdf(connection, sql) :
  Data has zero rows, returning an empty data frame

Study configuration (I did not use any excluded concept, which I realize is not good but I don't think the cause of the error):

covarSettings <- createCovariateSettings(useCovariateDemographics = TRUE,
                                         useCovariateConditionOccurrence = TRUE,
                                         useCovariateConditionOccurrence365d = TRUE,
                                         useCovariateConditionOccurrence30d = TRUE,
                                         useCovariateConditionOccurrenceInpt180d = TRUE,
                                         useCovariateConditionEra = TRUE,
                                         useCovariateConditionEraEver = TRUE,
                                         useCovariateConditionEraOverlap = TRUE,
                                         useCovariateConditionGroup = TRUE,
                                         useCovariateDrugExposure = TRUE,
                                         useCovariateDrugExposure365d = TRUE,
                                         useCovariateDrugExposure30d = TRUE,
                                         useCovariateDrugEra = TRUE,
                                         useCovariateDrugEra365d = TRUE,
                                         useCovariateDrugEra30d = TRUE,
                                         useCovariateDrugEraEver = TRUE,
                                         useCovariateDrugEraOverlap = TRUE,
                                         useCovariateDrugGroup = TRUE,
                                         useCovariateProcedureOccurrence = TRUE,
                                         useCovariateProcedureOccurrence365d = TRUE,
                                         useCovariateProcedureOccurrence30d = TRUE,
                                         useCovariateProcedureGroup = TRUE,
                                         useCovariateObservation = TRUE,
                                         useCovariateObservation365d = TRUE,
                                         useCovariateObservation30d = TRUE,
                                         useCovariateObservationCount365d = TRUE,
                                         useCovariateMeasurement365d = TRUE,
                                         useCovariateMeasurement30d = TRUE,
                                         useCovariateMeasurementCount365d = TRUE,
                                         useCovariateMeasurementBelow = TRUE,
                                         useCovariateMeasurementAbove = TRUE,
                                         useCovariateConceptCounts = TRUE,
                                         useCovariateRiskScores = TRUE,
                                         useCovariateRiskScoresCharlson = TRUE,
                                         useCovariateRiskScoresDCSI = TRUE,
                                         useCovariateRiskScoresCHADS2 = TRUE,                                         
                                         useCovariateInteractionYear = FALSE,
                                         useCovariateInteractionMonth = FALSE,
                                         deleteCovariatesSmallCount = 100)

cohortMethodData <- getDbCohortMethodData(connectionDetails,
                                          cdmDatabaseSchema = cdmDatabaseSchema,
                                          oracleTempSchema = resultsDatabaseSchema,
                                          targetId = 1082,
                                          comparatorId = 1081,
                                          indicationConceptIds = c(),
                                          washoutWindow = 183,
                                          indicationLookbackWindow = 183,
                                          studyStartDate = "",
                                          studyEndDate = "",
                                          outcomeIds = 1080,
                                          outcomeConditionTypeConceptIds = c(),
                                          exposureDatabaseSchema = resultsDatabaseSchema,
                                          exposureTable = "CATH_STUDY",
                                          outcomeDatabaseSchema = resultsDatabaseSchema,
                                          outcomeTable = "CATH_STUDY",
                                          excludeDrugsFromCovariates = FALSE,
                                          covariateSettings = covarSettings,
                                          cdmVersion = cdmVersion)

**Comment by jduke99** [comment]
Here is my platform information:

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Platform: x86_64-apple-darwin13.4.0 (64-bit)

**Comment by schuemie** [comment]
Hi Jon. This seems like a know issue, where one of the data sets retrieved has zero rows. Most likely there are no outcomes at all for your cohorts of interest.

Instead of trying to add workarounds for all situations like these, I've decided to try and solve the root cause: ff doesn't allow zero row objects. I'm working with the original developers of ff, but it is slow progress.

**Comment by jduke99** [comment]
Thanks Martijn.  So this points perhaps to my own lack of understanding of setting up a CM run.   I have created three cohorts (using Circe).    Here they are on ohdsi.org if helpful:

Target - http://www.ohdsi.org/web/circe/#/814
Comparator - http://www.ohdsi.org/web/circe/#/815
Outcome - http://www.ohdsi.org/web/circe/#/816

I have confirmed that all three cohorts have been generated in my database and that there is overlap of subject_ids between my target / comparator and outcome cohorts (doing SQL joins to check).

I moved these three cohorts to a dedicated table (cath_study).  I reference the local cohort__definition_ids in my CM configuration.  I did not use any exclusion criteria in this particular run, just to test it out.  But I am trying to understand why my data frame would be empty.  My configuration is in the post above.  Am I missing something (or alternatively have left in a configuration that I should have taken out)?

**Comment by jduke99** [comment]
I will close issue and post this question via the forums.

**Comment by schuemie** [comment]
Hi Jon. You may want to try the latest version of CohortMethod. I found that I had not considered situations where people have outcomes, but no prior outcomes, and because of the ff limitations that again led to an error. The new version has a workaround (but I really need to get the ff package fixed).

**Comment by jduke99** [comment]
Thank you Martijn.  That was my study exactly-- no prior outcomes, all are post.  I will install and re-run with the latest.

One thought:  Would it make sense to do a "check" for empty outcomes at the beginning of the process rather than later?  And if empty, just jump out before churning through all the covariates?

**Comment by jduke99** [comment]
@schuemie , I got this error when trying to load the updated CohortMethod.  I deleted and re-installed the package and still the same error.  I figured since it is a corruption issue it was related to my folders, but I go the same error on my Mac and PC. Any ideas?

library(CohortMethod)
Error in get(method, envir = home) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/CohortMethod/R/CohortMethod.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘CohortMethod’

**Comment by schuemie** [comment]
Ughhh, I don't understand what is happening. I can reinstall and load CohortMethod just fine on my machine. The problem seems to be an R problem, although I have no clue why it is happening on both your Mac and PC. 

Some googling on this problem suggests most people solve it by restarting R, but you've tried that. [Here](https://groups.google.com/forum/#!topic/h2ostream/LwmFC1ec9EY) they suggest unloading the package and then restarting R. You can unload the package using
```r
detach("package:CohortMethod", unload = TRUE)
```

**Comment by jduke99** [comment]
Okay, detached, uninstalled, quit R, restarted, reinstalled, and it all appears to work this time. :)

Will re-run with my analysis from the other day and see how things go.
