### ISSUE TITLE
How to treat the patients in CohortMethod if the patients took exposure and comparator drugs on the index date?

### ISSUE THREAD

**Issue by zuoyizhang** [OHDSI/CohortMethod#45]

**Comment by schuemie** [comment]
In the upcoming v3.0.0, the following behavior is implemented, depending on the `removeDuplicateSubjects` argument of `createStudyPopulation`:
- 'keep all' or FALSE: Patient is counted twice
- 'remove all' and 'keep first': Patient is removed
