### ISSUE TITLE
Variable case inconsistency

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/CohortMethod#47]
line 848 in PsFunctions.R has an inconsistent case in the name of the variable.  It is currently
beforeMatchingsumComparator - should it be beforeMatchingSumComparator?

A minor issue but I noticed this when working through the comparative cohort analysis workflow and the SqlRender function converting camel case to snake case bit me with this issue.

**Comment by fdefalco** [comment]
I've committed a proposed fix in the fix-47 branch.

**Comment by schuemie** [comment]
Thanks for finding and fixing this. I've merged fix-47 with master.
