### ISSUE TITLE
New parameter to restrict cohorts to common time period

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/CohortMethod#54]
When comparing two treatments, it may be possible to select treatments which are not both available at the same time period, so therefore during the non-overlapping time, they do not represent valid counterfactual comparisons.    For example, when comparing two drugs, one approved in 2013 and another approved in 2014, the only valid time to base a comparison would be 2014 onward, because the second treatment wasn't available in 2013 (and any propensity score would warn in this if INDEX_YEAR were included in the model).    A proposed solution:  provide a analysis parameter to: 'limit cohorts to period of overlapping calendar time',  which would restrict the data to the maximum of the minimum cohort start dates of the two cohorts, and would run through the minimum of the maximum time-at-risk end dates.

**Comment by pbr6cornell** [comment]
This restriction would need to be included in the Attrition plot also, if set = TRUE by the user, so that you can see how many patients were removed from each cohort as a result of the 'common time period' restriction.

**Comment by schuemie** [comment]
Just added an argument `restrictToCommonPeriod` to both `getDbCohortMethodData` and `createStudyPopulation` functions. (similar to the `firstExposureOnly`, `removeDuplicateSubjects`, and `washoutPeriod` arguments). The results from this restriction will be visible in the attrition diagram, although when using the `getDbCohortMethodData` the attrition will be grouped with the other three filters.

Could you check if this fits your needs?
