### ISSUE TITLE
Store relative paths in multi-analysis cohort method results

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/CohortMethod#61]
Currently, when generating in multi-analysis mode in CohortMethod, the outcomeModelReference.rds dataset contains absolute paths to the various datasets (like study population).  This introduces a problem when you want to move the output to a different directory, and the absolute paths are invalid.

I propose that if you just store the relative paths from a 'outputRoot' folder, you don't run into this issue. However, this does mean that when you want to process the cohort method results, you will need to provide an 'outputDirectory' root path that is prefixed to all the paths in the outcomeModelReference.rds, but from what I can tell about how 'pacakgeResults' and 'createTableAndFigures' works, you always need to provide an output folder when invoking those methods anyway.

**Comment by schuemie** [comment]
In develop branch now
