### ISSUE TITLE
Start / end of study [follow-up period]

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortMethod#66]
We should be recording two very simple statistics in the CohortMethod:

	1. min( index data ) across patients -- "start of study"
	2. max( last observation date ) across patients -- "end of study"

**Comment by schuemie** [comment]
Do you want 

1. The start / end when follow-up was eligible (but maybe didn't occur).

Or 

2. The start / end that was actually observed

In the case of 2, do you want

  2.a. Observed in the data as found in the cohort table

  2.b. Observed after applying `createStudyPopulation`

  2.c. Observed after matching / trimming / stratification

Should these dates be added to the table created by `summarizeAnalyses`?
