### ISSUE TITLE
Default value of plotCovariateBalanceOfTopVariables function's 'n' argument.

### ISSUE THREAD

**Issue by Hazealign** [OHDSI/CohortMethod#70]
I found some issue when I exporting plots after CohortMethod analysis.

 - **Log**
```r
Fitting model at optimal hyperparameter
Using prior: Laplace(1.23356) None
Creating propensity scores took 12.4 secs
*** Adding propensity scores to study population objects ***
  |======================================================================| 100%
*** Trimming/Matching/Stratifying ***
  |======================================================================| 100%
*** Computing covariate balance ***
  |======================================================================| 100%
*** Fitting outcome models ***
  |======================================================================| 100%
Warning: Removed 1 rows containing missing values (geom_hline).
Warning: Removed 1 rows containing missing values (geom_vline).
Error in x[nc > (n - 3)] <- paste("...", substr(x[nc > (n - 3)], nc[nc >  :
  NAs are not allowed in subscripted assignments
> traceback()
6: .truncRight(as.character(filtered$covariateName), maxNameWidth)
5: CohortMethod::plotCovariateBalanceOfTopVariables(balance) at Code.R#453
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("./Code.R")
  ```
 - **Error Point**
![image](https://user-images.githubusercontent.com/1115741/47710820-15d06d00-dc77-11e8-9f44-b848dd6a2729.png)

I tried to find why this error happened, and I found the reason.
In `CohortMethod::plotCovariateBalanceOfTopVariables`([Link](https://github.com/OHDSI/CohortMethod/blob/v2.6.2/R/PsFunctions.R#L1144)), It's default `n` argument value is 20.

And I checked `balance` variable's row length. It was 18. In `plotCovariateBalanceOfTopVariables` function, it makes `topBefore` and `topAfter` using with `n` argument. So if length of covariates is lower than 20, It makes error. 

Is there any reason about `n` argument's default value is 20?
I think it'll be better to have a row length of balance than current value(20).

Thanks. :)

**Comment by schuemie** [comment]
PS We typically have >10,000 covariates, so we didn't run into this issue before. Although FeatureExtraction allows you to construct smaller sets of covariates, it is recommended to use the default set (`FeatureExtraction::createDefaultCovariateSettings()`)
