### ISSUE TITLE
An error occurred in ParallelLogger::clusterApply.

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/CohortMethod#76]
This is an error.

Thread 1 returns error: "java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer" when using argument(s): list(args = list(connectionDetails = list(dbms = "sql server", user =.......

Error in ParallelLogger::clusterApply(cluster, objectsToCreate, createCmDataObject) : 
  Error(s) when calling function 'fun', see earlier messages for details

I have never touched a setting... how to solve..?

**Comment by schuemie** [comment]
Can you run with `getDbCohortMethodDataThreads = 1` to get a more informative error message?

**Comment by SungJun9212** [comment]
Thank you for quick response.

Where should I run that??

**Comment by schuemie** [comment]
I assume you're calling `runAnalyses` somewhere? You can also just try settings `maxCores = 1` if you're running someone else's study code.

**Comment by SungJun9212** [comment]
thanks. 
it is my mistake.
i did not know the latest version 3.2 version.

but i have an another error..

why so many error in my cohortmethod?
i did not fully understand cohort method.


and do you know this error?

-------------------------------------

1 returns error: "unable to open" when using argument(s): list(analysisId = 1, targetId = 1194, comparatorId = 1193, outcomeId = 1195, includedCovariateConceptIds = 1, excludedCovariateConceptIds = 1, outcomeOfInterest = TRUE, cohortMethodDataFolder = "CmData_l1_t1194_c1193", studyPopFile = "StudyPop_l1_s1_t1194_c1193_o1195.rds", sharedPsFile = "Ps_l1_s1_p1_t1194_c1193.rds", psFile = "Ps_l1_s1_p1_t1194_c1193_o1195.rds", strataFile = "StratPop_l1_s1_p1_t1194_c1193_s1_o1195.rds", prefilteredCovariatesFolder = "", outcomeModelFile = "Analysis_1/om_t1194_c1193_o1195.rds"),/home/user/test/cmOutput,/home/user/test/balance
  |================================================================================================================================================================================| 100%
Error in ParallelLogger::clusterApply(cluster, subset, computeCovariateBalance,  : 
  Error(s) when calling function 'fun', see earlier messages for details


-----------------------------------

Thank you for your kindness.   :)

**Comment by schuemie** [comment]
The error message suggests some problem with ff files. Possibly you have no more space left in your fftemp folder? You can check where that is using
```r
getOption("fftempdir")
```

**Comment by SungJun9212** [comment]
thanks.
but there is a lot of space left in the fftemp folder.

Do I need to set fftempdir and outputFolder differently?

If it is not,,
Is there another suspicion?

**Comment by schuemie** [comment]
You could set fftempdir to the same as the outputFolder, but it is much better to put them in separate folders. Sometimes not all temp files are cleaned up, and then you can easily delete all files in the fftemp folder (when all R instances are closed) without having to worry you are deleting something important.

I always set
```r
options(fftempdir = "c:/FFtemp")
```
and make sure c:/fftemp exists.

Perhaps there's another problem. Maybe you can use a logger to catch the error? You can type
```r
ParallelLogger::addDefaultFileLogger("c:/log.txt")
```
Before running runCmAnalyses to start a log file. (You can of course put the log file in a different location if you want).
