### ISSUE TITLE
Update SqlRender code in vignette

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortMethod#80]
I am working through the single studies vignette (which is very useful, thanks!), and I think some of the SqlRender code needs to be updated as some of the functions are now depreciated.

Am I right in changing:
"library(SqlRender)
sql <- readSql("coxibVsNonselVsGiBleed.sql")
sql <- renderSql(sql,
               cdmDatabaseSchema = cdmDatabaseSchema,
               resultsDatabaseSchema = resultsDatabaseSchema)$sql" 
to
"library(SqlRender)
sql <-  readSql("coxibVsNonselVsGiBleed.sql")
sql <- render(sql,
                 cdmDatabaseSchema = cdmDatabaseSchema,
                  resultsDatabaseSchema = resultsDatabaseSchema) 
sql <- translate(sql, targetDialect = connectionDetails$dbms)"

and
"sql <- paste("SELECT cohort_definition_id, COUNT(*) AS count",
"FROM @resultsDatabaseSchema.coxibVsNonselVsGiBleed",
"GROUP BY cohort_definition_id")
sql <- renderSql(sql, resultsDatabaseSchema = resultsDatabaseSchema)$sql
sql <- translateSql(sql, targetDialect = connectionDetails$dbms)$sql"
to
sql <- paste("SELECT cohort_definition_id, COUNT(*) AS count",
"FROM @resultsDatabaseSchema.coxibVsNonselVsGiBleed",
"GROUP BY cohort_definition_id")
sql <- render(sql, resultsDatabaseSchema = resultsDatabaseSchema)
sql <- translate(sql, targetDialect = connectionDetails$dbms)"

**Comment by schuemie** [comment]
Done
