### ISSUE TITLE
could not find function "getCounts"

### ISSUE THREAD

**Issue by CHUNGGAK** [OHDSI/CohortMethod#83]
Hi.
That error occurs during fitting outcome models.
I am looking for getCounts() function in OHDSI github and R reference manuals to activate the function.
However I could not find the function.
Actually I found one but it was not.
(https://bioconductor.org/packages/release/bioc/manuals/edgeR/man/edgeR.pdf)

**Comment by schuemie** [comment]
[Here](https://github.com/OHDSI/CohortMethod/blob/d6f6457e397e5b8882d10b7d186b7fdd8cc34369/R/StudyPopulation.R#L284) it is.

The reason for the error message may be that the package wasn't built (correctly). Did you follow the [installation instructions](https://ohdsi.github.io/CohortMethod/#installation)?

**Comment by CHUNGGAK** [comment]
Thank you for a quick reply!

I am using CohortMethod package in offline environment. Therefore I can not follow installation instructions.
Is there an offline installation guide?
I downloaded the CohortMethod ZIP file in github and used "install.packages(repos = NULL, type = "source")" function.
