### ISSUE TITLE
edge case where cmData raw cohort count and attrition "original population" count don't match

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/CohortMethod#85]
when using studyStartDate and studyEndDate in getDbCohortMethodData, the cohort start date must be <= study end date:
https://github.com/OHDSI/CohortMethod/blob/master/inst/sql/sql_server/CreateCohorts.sql#L226

but later when counting the original cohort sizes for the attrition table, the cohort start date must be < study end date:
https://github.com/OHDSI/CohortMethod/blob/master/inst/sql/sql_server/CountOverallExposedPopulation.sql#L80

adding <= the line 80 of CountOverallExposedPopulation.sql aligns the counts in the rare occurrences where this matters

**Comment by schuemie** [comment]
Thanks! Feel free to create a pull request (please target the develop branch).
