### ISSUE TITLE
Error writing Kaplan_Meier_dist csv

### ISSUE THREAD

**Issue by jduke99** [OHDSI/CohortMethod#87]
I frequently get this error when running cohort studies

![image](https://user-images.githubusercontent.com/5069947/64481564-d1253480-d1ab-11e9-8d18-2de4fc785e29.png)

I believe it is due to not writing out or not producing a Kaplan Meier dist file.  Have you seen this and do you have any idea the cause?

**Comment by schuemie** [comment]
Do you have a link to the study package, so I can reproduce the error?
