### ISSUE TITLE
Can't install CohortMethod

### ISSUE THREAD

**Issue by yahou00** [OHDSI/CohortMethod#88]
I have trouble in "CohortMethod" installation.
--------------------------------------------------
Below is the part of my boss code and I would like to run the whole code to produce some plots. 

devtools::install_github("OHDSI/Cyclops")
library(devtools)
library(Cyclops)

install.packages("drat")
drat::addRepo("OHDSI")
install.packages("CohortMethod") # Only need to run once to install package locally

data_directory = "C:/Users/yahou/Desktop/GrahamStudy" # Change to your location

library(CohortMethod)
cohortMethodData <- loadCohortMethodData(paste0(data_directory, "cohortMethodDataAllCovars"))
summary(cohortMethodData) # basic info on data
......

-------------------------

I followed all the installation instructions but it seems like "CohortMethod" has never been installed. Would you please help me to install this correctly? I am a beginner so it would be nice if you give me detailed instructions.
This is the message after running install.packages.

> install.packages("CohortMethod")
Installing package into ‘C:/Users/Jiyoonkim/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
also installing the dependencies ‘FeatureExtraction’, ‘SqlRender’

Warning in install.packages :
  unable to access index for repository https://OHDSI.github.io/drat/bin/windows/contrib/3.5:
  cannot open URL 'https://OHDSI.github.io/drat/bin/windows/contrib/3.5/PACKAGES'

  There is a binary version available but the source version is later:
          binary source needs_compilation
SqlRender  1.6.2  1.6.3             FALSE

Packages which are only available in source form, and may need compilation of C/C++/Fortran: ‘FeatureExtraction’
  ‘CohortMethod’
installing the source packages ‘FeatureExtraction’, ‘SqlRender’, ‘CohortMethod’

trying URL 'https://OHDSI.github.io/drat/src/contrib/FeatureExtraction_2.2.5.tar.gz'
Content type 'application/gzip' length 1024420 bytes (1000 KB)
downloaded 1000 KB

trying URL 'https://OHDSI.github.io/drat/src/contrib/SqlRender_1.6.3.tar.gz'
Content type 'application/gzip' length 390122 bytes (380 KB)
downloaded 380 KB

trying URL 'https://OHDSI.github.io/drat/src/contrib/CohortMethod_3.1.0.tar.gz'
Content type 'application/gzip' length 1281879 bytes (1.2 MB)
downloaded 1.2 MB

'C:\PROGRA~1\R\R-35~1.1/bin/x64/Rterm.exe' is not recognized as an internal or external command,
operable program or batch file.
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘SqlRender’ had non-zero exit status
'C:\PROGRA~1\R\R-35~1.1/bin/x64/Rterm.exe' is not recognized as an internal or external command,
operable program or batch file.
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘FeatureExtraction’ had non-zero exit status
'C:\PROGRA~1\R\R-35~1.1/bin/x64/Rterm.exe' is not recognized as an internal or external command,
operable program or batch file.
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘CohortMethod’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\yahou\AppData\Local\Temp\RtmpcP9ax8\downloaded_packages’
> find.package("CohortMethod")
Error in find.package("CohortMethod") : 
  there is no package called ‘CohortMethod’

Thank you!!

**Comment by schuemie** [comment]
There might be something wrong with your R installation. See this error message:
```
C:\PROGRA1\R\R-351.1/bin/x64/Rterm.exe' is not recognized as an internal or external command,
operable program or batch file.
```

Did you install [RTools](https://cran.r-project.org/bin/windows/Rtools/)? 

If so, maybe trying to reinstall R may help? (This would also allow you to get the latest version)
