### ISSUE TITLE
Review for the new function to apply external PS model on the population of interest

### ISSUE THREAD

**Issue by chandryou** [OHDSI/CohortMethod#89]
As one of the METIS project, it is required to make the new function apply external ps model on population of interest.

I've made a new function named 'predict' (just like predict function in PLP package)
@msuchard @schuemie  Could you review [this code](https://github.com/ABMI/CohortMethod/blob/metis/R/predict.R)?

**Comment by schuemie** [comment]
Hi Chan. 

I recommend putting all experimental code like this in the Metis package instead. I would prefer not to have functions in CohortMethod that represent a practice that we haven't yet evaluated.

**Comment by chandryou** [comment]
Ok- I agree!
