### ISSUE TITLE
Question on the createCmTable1 function

### ISSUE THREAD

**Issue by gyeol99** [OHDSI/CohortMethod#90]
Hi, I'm currently exploring the CohortMethod R package. I didn't know whether to post this question on the Forums or here. Hope this is appropriate.

When I run the createCmTable1 function, I'm only able to retrieve the characteristics of age groups and gender. However, I would like to see the baseline characteristics of all the covariates I selected for the PS matching process, like the example listed [here](https://ohdsi.github.io/CohortMethod/articles/SingleStudies.html).

Did the example involve any custom coding or is the createCmTable1 function supposed to do this for me?

**Comment by schuemie** [comment]
No special coding is required, the example should work as described in the vignette. 

How 'mature' is your CDM? Did you run [ACHILLES](https://www.ohdsi.org/analytic-tools/achilles-for-data-characterization/)?

**Comment by gyeol99** [comment]
Hi Martijn. Yes, we ran ACHILLES on our database and we don't have any errors in ACHILLES Heel.
