### ISSUE TITLE
Deprecate excludeDrugsFromCovariates argument in getDbCohortMethodData

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortMethod#93]
It does not seem to be used by anyone

**Comment by chandryou** [comment]
Then, I think `excludeDrugsFromCovariates` argument should be removed from the function, or it would be better to set `excludeDrugsFromCovariates = FALSE` as default. 

Currently, the code below makes a following error, 

```
CohortMethod::createGetDbCohortMethodDataArgs(covariateSettings = covariateSettings,
                                                                 excludeDrugsFromCovariates = F, 
                                                                 firstExposureOnly = TRUE,
                                                                 washoutPeriod = 183)
```

```
Error in get(name) : 
  argument "excludeDrugsFromCovariates" is missing, with no default
```

**Comment by schuemie** [comment]
Ah, yes, my bad. I just pushed a fix to the develop branch that will fix this. For now you can install from that branch, or just set `excludeDrugsFromCovariates = FALSE`
