### ISSUE TITLE
BigQuery. DDL operations:  Exceeded rate limits: too many table update operations for this table

### ISSUE THREAD

**Issue by YaroslavTir** [OHDSI/CohortMethod#94]
Running analysis against Big Query we got the following error.
We got an error when running analysis: 
```
DBMS:
bigquery
Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors
SQL:
DROP TABLE IF EXISTS result_schema.ush0u3excohort_person


drop table cohort_person"
```
https://cloud.google.com/bigquery/quotas#standard_tables

We analyzed this issue and have found that analysis recreates over and over the table with same {sessionId}cohort_person name. BigQuery has a limit for DDL operation 5 operations per 10 seconds, so we reach it: 
https://cloud.google.com/bigquery/quotas#standard_tables

Currently, we use one global sessionId per analysis run, and this means the same preposition for all temporary tables, and the same {sessionId}cohort_person table name in case if we call getDbCohortMethodData in the loop. The most logical solution is to use unique sessionId for all sql that we create between CreateCohorts.sql and RemoveCohortTempTables.sql
https://github.com/OHDSI/CohortMethod/blob/7099db8839b581a77a33191650063f7e15ca52ef/R/DataLoadingSaving.R#L199
https://github.com/OHDSI/CohortMethod/blob/7099db8839b581a77a33191650063f7e15ca52ef/R/DataLoadingSaving.R#L390

This solution involves changing SqlRender and DatabaseConnection. That is straightforward changes(just pass a sessionid argument), but it looks like a lot of places should be patch this way.

**Comment by schuemie** [comment]
Perhaps another approach: I know we want to be as efficient as possible, but maybe sometimes we just wait a few seconds so as to stay within the BigQuery quota? This could be enforced at the DatabaseConnector level, where for BigQuery it can keep track per connection how many queries of a specific type have been launched recently.

I'm surprised you are actually hitting the quota here. In most studies there is at least a few minutes (to contruct the covariates) between creating and deleting the temp table. Or is that not the problem?

**Comment by konstjar** [comment]
> I'm surprised you are actually hitting the quota here. In most studies there is at least a few minutes (to construct the covariates) between creating and deleting the temp table. Or is that not the problem?

Yes, we thought too, but COVID19 studies showed us that there are still few issues related to BQ limits. For your information, we met 2 types of limits issues:

**- DDL operations limits** 
Yes, covariates logic is executed faster when 10 sec in some cases. 
We were thinking to solve it on DatabaseConnector level by setting {sessionId} there, but unfortunately SQL logic "create table -> operations -> delete table" is placed in different SQL scripts and it's executed as separate sessions. So, there is no context on DatabaseConnector level where table is created and dropped. That's why we switched to {sessionId} approach to avoid setting 10sec delay between each query. Do you see better solution for this?

**- INSERT and UPDATE operations limits** 
We will propose independent solution with delays on DatabaseConnector level as a separate issue as you proposed.

**Comment by schuemie** [comment]
DDL operations limits: Maybe also solve these by having DatabaseConnector delay as needed? DROP TABLE statements are probably the easiest statements to find in SQL using a regex, and CREATE TABLE shouldn't be much harder. We can keep track per table when the last DDL operation was. If a new operation is issues within the minimum time, just delay as long as needed to meet the minimum.

**Comment by YaroslavTir** [comment]
> DDL operations limits: Maybe also solve these by having DatabaseConnector delay as needed? DROP TABLE statements are probably the easiest statements to find in SQL using a regex, and CREATE TABLE shouldn't be much harder. We can keep track per table when the last DDL operation was. If a new operation is issues within the minimum time, just delay as long as needed to meet the minimum.

sure we can do this. since the limit is `5 operations every 10 seconds per table`, 2 seconds will be more than enough for ddl. We used this workaround code for COVID

``` #' @export
#' @export
lowLevelExecuteSql.default <- function(connection, sql) {
  statement <- rJava::.jcall(connection@jConnection, "Ljava/sql/Statement;", "createStatement")
  on.exit(rJava::.jcall(statement, "V", "close"))

  start <- Sys.time()
  hasResultSet <- rJava::.jcall(statement, "Z", "execute", as.character(sql), check = FALSE)

  if (connection@dbms == "bigquery") {
    value <- toupper(sql)
    value <- sub("^\\s+", "", value)

    if (startsWith(value, 'INSERT')) {
      InsertThreshold = 5
      delta = Sys.time() - start
      if (delta < InsertThreshold) {
        Sys.sleep(InsertThreshold - delta)
      }
    } else if (startWith(value, 'DROP')) {
      DDLthreshold = 2
      delta = Sys.time() - start
      if (delta < DDLthreshold) {
        Sys.sleep(DDLthreshold - delta)
      }
    }
  }

  rowsAffected <- 0
  if (!hasResultSet) {
    rowsAffected <- rJava::.jcall(statement, "I", "getUpdateCount", check = FALSE)
  }
  invisible(rowsAffected)
}
```
InsertThreshold is keep track per table should not be complicated.

**Comment by YaroslavTir** [comment]
I wrote a delayIfNecessary as example. So we can add it into DatabaseConnector for insert and ddl queries. 
```
library(stringr)
ddlList = list()
insertList = list()
```
```
delayIfNecessary <- function(sql, querySqlExecutionByTabl, threshold, regex) {
    groups <- str_match(sql, regex(regex, ignore_case = TRUE))
    tableName <- groups[3]
    if (! is.na(tableName) && ! is.null(tableName)) {

        currentTime <- Sys.time();
        lastExecutedTime <- querySqlExecutionByTabl[[tableName]]
        if (! is.na(lastExecutedTime) && ! is.null(lastExecutedTime)) {
            delta <- currentTime - lastExecutedTime
            if (delta < threshold) {
                Sys.sleep(threshold - delta)
            }
        }
        querySqlExecutionByTabl[[tableName]] = currentTime
    }
    return(querySqlExecutionByTabl)
}
```
```
ddlList <- delayIfNecessary(sql, ddlList, 2,
"(^CREATE\\s+TABLE|^CREATE\\s+TABLE\\s+IF\\s+EXITS|^DROP\\s+TABLE|^DROP\\s+TABLE\\s+IF\\s+EXITS)\\s+([a-zA-Z0-9_$#-]*\\.?\\s*(?:[a-zA-Z0-9_]+)*)");

insertList <- delayIfNecessary(sql, insertList, 5,
"(^INSERT\\s+INTO)\\s+([a-zA-Z0-9_$#-]*\\.?\\s*(?:[a-zA-Z0-9_]+)*)");
```

**Comment by YaroslavTir** [comment]
@schuemie what do you think about a solution like this? Is it good enough? I am currently testing it, if it is alright and you agree with the code above then I can create a pull request.

**Comment by schuemie** [comment]
Yes, looks good. I think `ddlList` and `insertList` are intended to be global variables? Right now their scope us just the function. To keep them between calls I recommend using `options`, like [here](https://github.com/OHDSI/ParallelLogger/blob/master/R/Logging.R#L61).

**Comment by YaroslavTir** [comment]
oh, super, good to know :)

**Comment by YaroslavTir** [comment]
@schuemie I wrote a code and test it (https://github.com/odysseusinc/DatabaseConnector/commit/25f3395ace670a4e9ac3168d95b17d3f7482ef86), but did not create PR yet, for a few reasons:
* to work with regexp I need `library(stringr)` I a little bit confused where should I put it.
* it is nice to have created a unit test, but I am worried to break something. Do you run tests automatically?

**Comment by schuemie** [comment]
In R packages you're not supposed to call `library`, as this will have unintended side-effects for the user of your package. Instead, what you do is:
1. Add `stringr` to the [Imports section in the DESCRIPTION file](https://github.com/OHDSI/DatabaseConnector/blob/master/DESCRIPTION#L20).
2. Use explicit package references in your code, so in this case `stringr::str_match()`.

In this case I wouldn't worry about a unit test. It would be nice to have, but we don't have a testing framework available for BigQuery. (Yes, unit tests are executed automatically by travis)

**Comment by YaroslavTir** [comment]
Thank you for the tip. It took some time to properly test the fix, but now it is ready:
https://github.com/OHDSI/DatabaseConnector/pull/122
