### ISSUE TITLE
Adding PS overlap weight

### ISSUE THREAD

**Issue by chandryou** [OHDSI/CohortMethod#96]
It might be beneficial to add PS overlap weight (an alternative to the IPTW), which was suggested by Li et al. (Li, Fan, Laine E. Thomas, and Fan Li. “Addressing Extreme Propensity Scores via the Overlap Weights.” American Journal of Epidemiology 188, no. 1 (01 2019): 250–57. https://doi.org/10.1093/aje/kwy201.).

PS overlap weight emphasizes the portion of the population where the most treatment equipoise exists in clinical practice, and this method seems more robust than IPTW. 

The overlap weight can be calculated as below:
`population$weights <- ifelse(population$treatment==1,1-data$ps,data$ps)`

**Comment by anthonysena** [comment]
[HADES Hack-a-thon]: Justin is going to work on this item.

**Comment by jmb01** [comment]
#127 has implemented the weight

**Comment by chandryou** [comment]
PS overlap weight exaggerates population in the overlap. I wonder how this affects on reliability of the method just like empirical equipose. ;)

@schuemie

**Comment by louisahsmith** [comment]
#129 is the improved pull request based on the develop branch

**Comment by chandryou** [comment]
Should we change all 'iptw' column name in dataframes into 'weightedPs'?

**Comment by schuemie** [comment]
This still needs to be fully integrated into the package (e.g. in the multiple-analyses framework).
