### ISSUE TITLE
`tbl_vars_dispatch` error following "No data found"

### ISSUE THREAD

**Issue by aki-nishimura** [OHDSI/CohortMethod#97]
I am running the study package [Covid19SusceptibilityAlphaBlockers](https://github.com/ohdsi-studies/Covid19SusceptibilityAlphaBlockers) and am getting the following error:
> INFO	FeatureExtraction		Fetching data took 0.73 secs
> WARN	FeatureExtraction		No data found
> FATAL	dplyr	tbl_vars_dispatch	Error in UseMethod("tbl_vars") :    no applicable method for 'tbl_vars' applied to an object of class "NULL" `

I had @msuchard take a look at the error and he says he has never seen this one before. Any idea what might be the cause and how to fix it? The full traceback below:

> Stack trace:
> 26: tbl_vars_dispatch(x)
> 25: structure(vars, groups = group_vars, class = c("dplyr_sel_vars", "character"))
> 24: new_sel_vars(tbl_vars_dispatch(x), group_vars(x))
> 23: tbl_vars(x)
> 22: "n" %in% tbl_vars(x)
> 21: tally_n(x, {
>     {
>         wt
>     }
> })
> 20: tally(out, wt = !!enquo(wt), sort = sort, name = name)
> 19: count(.)
> 18: function_list[[i]](value)
> 17: freduce(value, `_function_list`)
> 16: `_fseq`(`_lhs`)
> 15: eval(quote(`_fseq`(`_lhs`)), env, env)
> 14: eval(quote(`_fseq`(`_lhs`)), env, env)
> 13: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 12: covariateData$covariates %>% count() %>% pull()
> 11: .makeMessage(...)
> 10: log(level = "DEBUG", ...)
> 9: ParallelLogger::logDebug("Fetched covariates total count is ", covariateData$covariates %>% count() %>% pull())
> 8: getDbCohortMethodData(connectionDetails = ….
> 7: do.call("getDbCohortMethodData", params$args)
> 6: FUN(X[[i]], ...)
> 5: lapply(x, fun, ...)
> 4: ParallelLogger::clusterApply(cluster, objectsToCreate, createCmDataObject)
> 3: CohortMethod.R#60: CohortMethod::runCmAnalyses(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSch
> 2: Main.R#127: runCohortMethod(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, cohortDatabase
> 1: execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, cohortDatabaseSchema = cohortDatab

**Comment by msuchard** [comment]
My best guess is that the `Andromeda` object (that is probably empty) is behaving poorly in `covariateData$covariates %>% count() %>% pull()`.   @schuemie -- is there any easy fix?

**Comment by aki-nishimura** [comment]
Yep, #98 seems to fix the problem; the AlphaBlocker package got threw the error and is currently still running.

**Comment by aki-nishimura** [comment]
Turns out `(andromeda_obs)$element %>% count()` appears in several places in `CohortMethod` as well in `FeatureExtraction` (namely 7 occurrences in each package). It is easy enough to manually check for `NULL`, but maybe @schuemie has a cleaner solution.

**Comment by schuemie** [comment]
Hmmm, one of the big advantages of Andromeda over ff is that we can have zero-row tables. We definitely don't want to go back to the ff mess where we had to check for NULL everywhere. `covariates` shouldn't be NULL, but a zero-row table. 

Could you help find out why `covariates` does not exist? In FeatureExtraction if the population is empty a zero-row table is constructed [here](https://github.com/OHDSI/FeatureExtraction/blob/master/R/GetCovariates.R#L106) (with a reference to [this function](https://github.com/OHDSI/FeatureExtraction/blob/bfa7d6fe33a362d1c28598af4fac11249141f628/R/CovariateData.R#L192).) But apparently that code isn't reached in your case?

**Comment by schuemie** [comment]
I added some unit tests to try and reproduce the problem. The only way I could reconstruct it is if the covariateSettings were empty. One way this could happen is if you would use
```r
covariateSettings <- createCovariateSettings()
```
(In this case, you'd probably intended to use `createDefaultCovariateSettings()`.) I'll make it so `createCovariateSettings()` throws an error if no covariates are specified.

Do you know if this is what happened in your case?

**Comment by aki-nishimura** [comment]
Sorry for the delay in responding (I couldn't mess with `FeatureExtraction` while other OHDSI studies packages are running). 

I see the check for empty population in `getDbCovariateData`, but it seems that there is no check for empty covariate in `getDbDefaultCovariateData`? I only know `getDbDefaultCovariateData` is called somewhere within `getDbCovariateData`, but not sure where exactly (probably an implicit call via  `get(function_name)` or something along the line).

I added the following logging info around the potential suspects (https://github.com/OHDSI/CohortMethod/commit/59a7d117ca9a6475d8691b3350dd15c5ed706dce, https://github.com/OHDSI/FeatureExtraction/commit/29fed2013e13d1a114e4ab6eb6652587c96d4b98) and here is the log.txt output:

> 2020-07-16 12:24:36	[Main thread]	INFO	CohortMethod	getDbCohortMethodData	FeatureExtraction::getDbCovariateData() is about to be called.
2020-07-16 12:24:36	[Main thread]	INFO	FeatureExtraction	getDbCovariateData	getDbCovariateData() is being called.
2020-07-16 12:24:37	[Main thread]	INFO	FeatureExtraction	getDbCovariateData	About to check for zero population size.
2020-07-16 12:24:37	[Main thread]	INFO	FeatureExtraction		getDbDefaultCovariateData() is being called.
2020-07-16 12:24:37	[Main thread]	INFO	FeatureExtraction		Constructing features on server
2020-07-16 12:24:39	[Main thread]	INFO	FeatureExtraction		Fetching data from server
2020-07-16 12:24:41	[Main thread]	INFO	FeatureExtraction		Fetching data took 2.03 secs
2020-07-16 12:24:46	[Main thread]	WARN	FeatureExtraction		No data found
2020-07-16 12:24:46	[Main thread]	INFO	CohortMethod	getDbCohortMethodData	Finished a call to FeatureExtraction::getDbCovariateData().
2020-07-16 12:24:46	[Main thread]	FATAL	dplyr	tbl_vars_dispatch	Error in UseMethod("tbl_vars") :    no applicable method for 'tbl_vars' applied to an object of class "NULL"

**Comment by schuemie** [comment]
But the only way I see that `covariates` can be `NULL` is if the `covariateSettings` object has no analysis specified (which in your study package does not seem the case). 

If there simply is no data from which to build covariates (which would be odd, because for example demographic covariates depend on obligatory fields), then we should have a zero-row `covariates` object, not a `NULL` one.

So I'm really stumped as to why `covariates` is NULL.

But where do the "...is about to be called." log messages come from? Are you sure you're running CohortMethod from the develop or master branch?

**Comment by aki-nishimura** [comment]
> Are you sure you're running CohortMethod from the develop or master branch?

Yes, I just added the log messages to `master` (and nothing else) for debugging purposes. (59a7d11, OHDSI/FeatureExtraction@29fed20)

As far as I can tell, `FeatureExtraction` seems to return `NULL` covariate here:
https://github.com/OHDSI/FeatureExtraction/blob/master/R/GetDefaultCovariates.R#L199

The `count(NULL)` error disappeared when I made this change:
https://github.com/OHDSI/FeatureExtraction/commit/577616d4eeb2bd708ddd0eb3aa0399098d60e38e

**Comment by schuemie** [comment]
Hi @aki-nishimura . Yes, there are several ways we can deal with the NULL `covariates` object after the fact (note that your current code always replaced the `covariateData` object with an empty one, even if there was data before). However, I'm keen on finding out *why* there is a NULL object. I can't think of a way this could happen, and I've run many scenarios now to try to reproduce this, and none of them create a NULL object. Having covariates is pretty important to the study, so just accepting that there are none without understanding why seems ill-advised.

In theory, `covariates` should not be NULL if the code reaches [this point](https://github.com/OHDSI/FeatureExtraction/blob/master/R/GetDefaultCovariates.R#L96). Could I bother you to run

```r
debug(FeatureExtraction:::getDbDefaultCovariateData)
```

and retry, seeing if the code reaches this point (and if not why not, and if it does, whether the covariate object is empty after the call)?

Alternatively, would it be possible to provide me with the exact data / code that reproduces this problem so I can debug myself?

**Comment by aki-nishimura** [comment]
Yes, it would be nice to find out why there would be no covariates.

The latest R version is apparently causing some troubles for RStudio and debugging tools do not work properly, but I added `logInfo()` before and after the call to `querySqlToAndromeda()` (https://github.com/OHDSI/FeatureExtraction/commit/5fa3eb4f417dfd84fa5ba688a24b91f41f1200be). Indeed, I see that the covariate is `NULL` only when `querySqlToAndromeda()` is not called, at least in my code:

(Non-empty covariate)
> 2020-07-20 19:30:19	[Main thread]	INFO	FeatureExtraction		getDbDefaultCovariateData() is being called.
2020-07-20 19:30:19	[Main thread]	INFO	FeatureExtraction		Sending temp tables to server
2020-07-20 19:30:39	[Main thread]	INFO	FeatureExtraction		Constructing features on server
2020-07-20 19:30:51	[Main thread]	INFO	FeatureExtraction		Fetching data from server
2020-07-20 19:30:51	[Main thread]	INFO	FeatureExtraction		About to query SQL to Andromeda.
2020-07-20 19:30:52	[Main thread]	INFO	FeatureExtraction		Query finished.
2020-07-20 19:30:53	[Main thread]	INFO	FeatureExtraction		Fetching data took 1.84 secs
2020-07-20 19:30:56	[Main thread]	INFO	CohortMethod	getDbCohortMethodData	Finished a call to FeatureExtraction::getDbCovariateData().

(Empty covariate)
> 2020-07-20 19:31:07	[Main thread]	INFO	FeatureExtraction		getDbDefaultCovariateData() is being called.
2020-07-20 19:31:07	[Main thread]	INFO	FeatureExtraction		Constructing features on server
2020-07-20 19:31:08	[Main thread]	INFO	FeatureExtraction		Fetching data from server
2020-07-20 19:31:08	[Main thread]	INFO	FeatureExtraction		Fetching data took 0.272 secs
2020-07-20 19:31:09	[Main thread]	WARN	FeatureExtraction		No data found

To reproduce the error, you can install the OHDSI study package `Covid19SusceptibilityAlphaBlockers@testing` and run this script:
https://github.com/ohdsi-studies/Covid19SusceptibilityAlphaBlockers/blob/testing/extras/CodeForMartijnToRun.R

**Comment by schuemie** [comment]
I'm unable to reproduce the problem, even when using the code you provided. My best guess is you are running some non-standard package version(s). I just used the latest versions on CRAN / GitHub master branches. 

I recorded the versions of all the packages I used [here](https://github.com/ohdsi-studies/Covid19SusceptibilityAlphaBlockers/blob/renv/renv.lock). 

A convenient way to reconstruct the same R environment I used is:
```r
# Install the latest version of renv:
install.packages("renv")

# Start a new project in RStudio (or when not using RStudio, create a new folder and 
# set it as the current working directory). When asked if you want to use renv with the 
# project, answer ‘no’.

# Download the lock file:
download.file("https://raw.githubusercontent.com/ohdsi-studies/Covid19SusceptibilityAlphaBlockers/renv/renv.lock", "renv.lock")
  
# Build the local library:
renv::init()
  
# When not in RStudio, you'll need to restart R now

# The study package can now be loaded and used:
library(Covid19SusceptibilityAlphaBlockers)
```

The code I ran to test is [here](https://github.com/ohdsi-studies/Covid19SusceptibilityAlphaBlockers/blob/renv/extras/CodeToRunMartijn.R).

**Comment by aki-nishimura** [comment]
Did you run it with the `testing` branch of `Covid19SusceptibilityAlphaBlockers`? (I wrote `@testing` in the previous comment, but sorry if it was not clear enough.)

As far as I can tell, we are are using the standard package versions; it would be best to try with the exact environment you provided, but I am not allowed to mess too much with the existing environment while other studies are ongoing.

**Comment by schuemie** [comment]
Ah, sorry, I missed the `@testing` bit. In that case, I am able to reproduce the problem, and have identified the root cause: for analysis 6 (Crude unadjusted), the covariate settings object has no covariates specified (all booleans are set to FALSE). 

I recommend instead using the same covariate settings for analysis 6 as one of the other analyses. CohorTMethod will recognize them as the same, and run the data fetch only once. Use the other analyses settings to disable PS adjustment.

**Comment by aki-nishimura** [comment]
Glad to know the root cause; thank you for looking into it.

It would be great to have an Atlas-generated analysis setting (`cmAnalysisList.json`) work fine in the future, but this is a great workaround to know.
