### ISSUE TITLE
"Error in xj[i]: only 0's may be mixed with negative subscripts" when a population table is empty

### ISSUE THREAD

**Issue by ablack3** [OHDSI/CohortMethod#99]
I'm trying to run the https://github.com/ohdsi-studies/TicagrelorVsClopidogrel study and kept getting a strange error `Error in xj[i]: only 0's may be mixed with negative subscripts`

I traced the problem to the `fastDuplicated` function running on an dataframe with zero rows. 

``` r
df <- data.frame(col1 = integer(), col2 = integer())
df
#> [1] col1 col2
#> <0 rows> (or 0-length row.names)
CohortMethod:::fastDuplicated(df, c("col1", "co2"))
#> Error in xj[i]: only 0's may be mixed with negative subscripts

# specifically the error is caused by this
df[1:(nrow(df) - 1), ]
#> Error in xj[i]: only 0's may be mixed with negative subscripts
```

<sup>Created on 2020-08-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not sure what the ideal behavior should be but this error causes the whole study execution to fail.

**Comment by schuemie** [comment]
I think you're running an old version? Nowadays `fastDuplicated` checks whether the object has zero rows. You still get an error on the next line though.

I [extended the unit tests for empty exposure cohorts, and fixed all the bugs that revealed](https://github.com/OHDSI/CohortMethod/commit/583657ea8ca2a15a91bb1d368a0fcd9ec71aa4d9). Could you give the version in the `develop` branch a try?

**Comment by ablack3** [comment]
I think I was using which is recommended in the study package [readme](https://github.com/ohdsi-studies/TicagrelorVsClopidogrel/blob/master/README.md)
 ` CohortMethod          * 3.0.2     Github (ohdsi/CohortMethod@ef66baf)   `

When I install the development branch of the CohortMethod package the `execute` function crashes my R session. This is just for my own learning as well as for tutorial preparation. I'm looking for a network study that will run on Synthea23m. I think there should be some pre-work done before attempting to execute a network study at least to make sure a cdm has enough data run the analysis.

**Comment by schuemie** [comment]
Yes, unfortunately you often can't run an old study using the new versions of the packages. And the old versions will throw errors when you run them on a database where the exposure cohorts are empty (which you could view as a bug or a feature).
